### ISSUE TITLE
Gruntfiles.github.io

### ISSUE THREAD

**Issue by grayghostvisuals** [chriscoyier/My-Grunt-Boilerplate#1]
Would you be willing to submit your standard `Gruntfile.js` and `package.json` to this small project? => [https://github.com/Gruntfiles/gruntfiles.github.io](https://github.com/Gruntfiles/gruntfiles.github.io)

**Comment by chriscoyier** [comment]
Probably. I'm just working through this right now. Few more days and I'll have a nice setup I think.
