### ISSUE TITLE
grunt not working

### ISSUE THREAD

**Issue by mohamedmohsin** [chriscoyier/My-Grunt-Boilerplate#12]
after the congfiguration ,grunt in terminal it said "'grunt' is not recognized as an internal or external command,operable program or batch file." help me out of this

**Comment by eduard-un** [comment]
I have this error after i type grunt

> > Error: Cannot find module 'glob'
> > Warning: Task "default" not found. Use --force to continue.

**Comment by mohamedmohsin** [comment]
@eduard-ungureanu 
module.exports = function (grunt) {
    grunt.initConfig({
        uglify : {
            my_target : {
                options : {
                    mangle : false
                },
                files : {
                    destination file name with path  : source file name with path
                }
            }
        }
    });
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.registerTask('default', ['uglify']);
};

simply run "grunt" in cmd it will run default task

**Comment by eduard-un** [comment]
i know the defaul one will work...i just need to make this boiler plate working...the one that Chris has created.... but thanks,

**Comment by eduard-un** [comment]
anyone can please let me know how to use this boilerplate?
I clone this repo to my desktop, open up the terminal, navigate to the folder, type: 
npm install grunt --save-dev
and then when i try to type grunt i get the message above....please anyone can point me in the right direction?

If i start with an empty project...everything works...but nothing works with this boilerplate!!!

Thank in advanced.

**Comment by sheabunge** [comment]
You need to run `npm install` when using an already made project, such as the boilerplate.

Also, make sure you have the global grunt-cli program installed:

`npm install -g grunt-cli`

**Comment by eduard-un** [comment]
@bungeshea , Thanks a lot mate...it worked now :dancer:
