### ISSUE TITLE
Dev vs Production

### ISSUE THREAD

**Issue by joshbetz** [chriscoyier/My-Grunt-Boilerplate#2]
I have some ideas based on previous experience with Grunt and didn't really know where to put this.

Here's a Gruntfile that I've used in the past: https://gist.github.com/joshbetz/8f6bd4acd504a0a15c21

The only thing I would change here is that I would make the "default" task run "watch". In my experience, you almost want to be running `grunt watch`, so I'd rather have that be the default. In your case, I would have "default" which is actually your "dev" right now and then "production" which minifies javascript, css, etc.

One of the nice things about this Gruntfile is that it defines the arrays for the tasks at the top, so you don't have to scroll to the bottom every time you want to change what happens.

**Comment by chriscoyier** [comment]
Good stuff man, thanks. The point of this repo for me is to kinda piledrive through it all myself and learn how it's done. Hopefully I can steal some ideas from yours! I haven't use it enough to be super opinionated on what the best task naming is.
