### ISSUE TITLE
Project files not showing in commit

### ISSUE THREAD

**Issue by mtsweir** [chriscoyier/My-Grunt-Boilerplate#20]
I've used this project to create my own local version, everything seems to run fine and grunt does the build with no errors.

But I can see that there are a number of folders that don't show as needing to be committed, things like: images, js, tasks

Also the main Gruntfile.js is not showing up either, is there something I've done wrong?

This is my gitignore file

```
# Build folders
/build
lib
dist
css

# Config files
.npmrc

# Runtime data
pids
*.csv
*.dat
*.gz
*.out
*.pid
*.seed

# Logs
logs
*.log
npm-debug.log

# Cache folders
.cache
.sass-cache

# Editor
.DS_Store
.vscode

# Dependency directory
node_modules

# Generated by npm@5
package-lock.json

# AAT test results from DAP/Axe
results/

```

---

And some screens showing the project status - with nothing to commit

<img width="317" alt="Screen Shot 2020-10-22 at 5 42 36 PM" src="https://user-images.githubusercontent.com/4976660/96825703-41654700-148e-11eb-9a67-91b415bb291d.png">

<img width="141" alt="Screen Shot 2020-10-22 at 5 42 47 PM" src="https://user-images.githubusercontent.com/4976660/96825709-43c7a100-148e-11eb-9588-172952856b98.png">

<img width="416" alt="Screen Shot 2020-10-22 at 5 45 00 PM" src="https://user-images.githubusercontent.com/4976660/96825744-52ae5380-148e-11eb-8286-042825162e71.png">

**Comment by chriscoyier** [comment]
I think you're on the right track looking at the .gitignore file there. I think those cascade too, so if there is one in a higher up directory it might effect it? I dunno, sorry. 

Just closing as I don't really have any intention of maintaining this project.
