### ISSUE TITLE
Define output paths in variables instead?

### ISSUE THREAD

**Issue by geoffyuen** [chriscoyier/My-Grunt-Boilerplate#8]
Pretty new to Grunt but your 24ways article really got me interested. I was wondering if it's possible to define output paths and files into variables in, say, the main Gruntfile.js? This way people could use this boilerplate on pre-existing projects and adapt the paths accordingly (for example img instead of images like in html5boilerplate).

**Comment by chriscoyier** [comment]
Just closing as I don't really have any intention of maintaining this project.
